# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20161111_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank='true', upload_to='uploads'),
        ),
    ]
